"""convert float fields to decimals

Revision ID: 80d9fd1dba9a
Revises: 95fb6e112ce5
Create Date: 2025-04-05 02:48:15.436829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d9fd1dba9a'
down_revision = '95fb6e112ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_block_list')
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('sales_tax',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=5),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('sales_tax',
               existing_type=sa.DECIMAL(precision=10, scale=5),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    op.create_table('token_block_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
